variables:
    IMAGE_NAME: ar-op-assist
    IMAGE_TAG: 0.1.0

stages:
    - test
    - build
    - deploy

build_image:
    stage: build
    image: docker:24.0.5
    services:
        -  docker:24.0.5-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login registry.gitlab.com -u $GITLAB_REGISTRY_USER -p $GITLAB_REGISTRY_PASSWORD
    script:
        - docker build -t registry.gitlab.com/$GITLAB_REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG .
        - docker push registry.gitlab.com/$GITLAB_REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG
