variables:
    - IMAGE_NAME: anduril5678/ar-op-assist
    - IMAGE_TAG: 0.1.0

stages:
    - test
    - build
    - deploy

build_image:
    stage: build
    image: docker:24.0.5
    services:
        -  doccker:24.0.5-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
