variables:
    IMAGE_NAME: ar-op-assist
    IMAGE_TAG: 0.1.0

stages:
    - build
    - deploy

build_image:
    tags:
        - Docker
    stage: build
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
    services:
        -   name: docker:24.0.5-dind
            alias: docker
            command: ["--tls=false"]
    script:
        - echo "$CI_JOB_TOKEN" | docker login registry.gitlab.com -u $CI_REGISTRY_USER --password-stdin
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker image tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        - docker image push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy_container:
    tags:
        - Shell
    stage: deploy
    script:
        - echo "$CI_DEPLOY_PASSWORD" | docker login registry.gitlab.com -u $CI_REGISTRY_USER --password-stdin
        - docker run -i -t --rm -p 1433:1433 -p 3000:3000 -v C:/Users/hw1048/Documents/AR-Operation-Assist-GitLab/output:/usr/src/app/output \
            "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

